from reportlab.platypus import SimpleDocTemplate,Paragraph , Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfgen import canvas
import uuid

def create_pdf(notes):
    filename=f"notes_{uuid.uuid4().hex}.pdf"
    doc=SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    content = []
    content.append(Paragraph("Notes",styles["Title"]))
    content.append(Spacer(1,20))
    lines = notes.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            content.append(Spacer(1,10))
            continue
        if line.startswith('##'):
            content.append(Paragraph(line.replace('##',""),styles['Headings2']))
        
        elif line.startswith("-"):
            content.append(Paragraph(line,styles['Normal']))
            content.append(Spacer(1,8))

        content.append(Spacer(1,20))
        content.append(Paragraph("Generated by AI study Assistant",styles["Italic"]))
    doc.build(content)
    return filename




    c.save()
    return filename








